package Bombercraft2.Bombercraft2;

public enum Options {
	RENDER_LOGS,
	RENDER_SUBMENU,
	RENDER_MINIMAP,
	RENDER_PLAYER_SELECTOR,
	RENDER_TOWERS,
	RENDER_SHADOWS,
	RENDER_PARTICLES,
	RENDER_LIGHTS,
	RENDER_BOMBS_RANGE,
	RENDER_ONLY_SHADOW_MAP,
	RENDER_HEALTH_BAR,
	RENDER_PLAYERS,
	RENDER_ENEMIES,
	RENDER_FLOOR_BLOCKS,
	RENDER_BLOCKS,
	RENDER_FLORA,
	RENDER_MOUSE_SELECTOR
}
